feat: nextjs migration
kubefirst/metaphor-frontend-template pull request #22
Opened 2022-11-16 18:28 UTC by CristhianF7

2022-11-16 19:24 UTC, pagottoo requested changes
our Dockerfiles need to be agnostic regarding the architecture

2022-11-16 19:24 UTC, pagottoo commented on build/Dockerfile
> +FROM --platform=linux/arm64 node:16-alpine AS builder
we need to remove the platform and let the docker choose based on the architecture of the node where the runner is running

2022-11-16 19:24 UTC, converge reviewed
nitpick one: there is a warning on `yarn dev` , maybe it's a good time to change it, since the refactor is touching different points. wdyt?

after `yarn dev`, the page loads ate localhost:3000, but its missing the K-ray logo at the top..

there is another warning in the console on `yarn dev`:
```
/!\ You are using legacy implementaion. Please update your code: use createWrapper() and wrapper.useWrappedStore().
4. withRedux(App) created new store with { initialState: undefined, initialStateFromGSPorGSSR: undefined }
4. withRedux(App) created new store with { initialState: undefined, initialStateFromGSPorGSSR: undefined }
4. withRedux(App) created new store with { initialState: undefined, initialStateFromGSPorGSSR: undefined }
The requested resource isn't a valid image for /static/kubefirst.png received text/html; charset=utf-8
```

2022-11-16 19:24 UTC, converge commented on build/Dockerfile
> +RUN adduser --system --uid 1001 nextjs
that's nice! ⭐

2022-11-16 19:24 UTC, converge commented on components/header/index.tsx
> +        <Image src="/static/kubefirst.png" alt="kubefirst logo" width="288" height="74" />
is it missing measure type?"288px" ?

2022-11-17 14:55 UTC, converge approved these changes

2022-11-17 15:27 UTC, pagottoo approved these changes
lgtm

2022-11-17 23:27 UTC, jarededwards approved these changes

2022-11-17 23:40 UTC, merged